#version: '3.8'
services:

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 124124
      MYSQL_DATABASE: board
    ports:
      - "3306:3306"

  board-api:
    image: board-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/board
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=124124
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect

volumes:
    mysql_volume:



#https://velog.io/@onetuks/docker-compose-%EA%B0%80-%ED%8C%8C%EB%86%93%EC%9D%80-%ED%95%A8%EC%A0%95
#dialect